config/routes.rb
Rails.application.routes.draw do
  resources :wishlist_items
  resources :gifts
  resources :wishlists
  devise_for :admins
  resources :events
  devise_for :users
  resources :welcome
  resources :events do
   resources :participations
 end
  resources :users

  get '/events/:id/participations', to: 'participations#create'
  post '/events/:id/participations', to: 'participations#create'

  root to: redirect('/welcome/show')
  post '/search', to: 'gifts#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/event.rb
class Event < ApplicationRecord
  validates :name, :description, :suggested_budget, :creator_id, presence: true

  belongs_to :creator, class_name: "User", foreign_key: :creator_id
  has_many :participations, dependent: :destroy
  has_many :participants, through: :participations, dependent: :destroy
  accepts_nested_attributes_for :participations

  def create_pairs
    participants = self.participants.shuffle
    nb_participants = participants.length
    temp = participants[0]
    assignees = Array.new(nb_participants, 0)
    participants.each_with_index do |elt, index|
      assignees[index] = participants[index+1]
    end
    assignees[(nb_participants-1)] = temp
    pairs = assignees.zip(participants)
    pairs.each_with_index do |elt, index|
      GiftExchange.create(recipient_id: elt[0].id, sender_id: elt[1].id, event_id: self.id, wishlist_item_id: 1)
    end
  end
end



# ALGORITHM 2
#   def assign
#       @participants_A = self.participants.dup.to_a
#       @participants_B = self.participants.dup.to_a
#     until @participants_A.length == 0
#       @participants_A.shuffle
#       @participants_B.shuffle
#       # binding.pry
#       group_a = @participants_A.pop
#       group_b = @participants_B.pop
#       if group_a == group_b && @participants_B.length == 1 && @participants_A.length == 1
#         animals = GiftExchange.find_by(event_id: self.id)
#         animals.destroy
#       elsif group_a == group_b
#         @participants_B.push(group_b)
#         pig = @participants_B.shift
#         GiftExchange.create(recipient: group_a, sender: pig, event_id: 1, wishlist_item_id: 1)
#       else
#         GiftExchange.create(recipient: group_a, sender: group_b, event_id: 1, wishlist_item_id: 1)
#       end
#     end
#   end
# end

# ALGORITHM 1
    # pairs = participants.shuffle
    # assignments = pairs.zip(participants)
    # assignments.each do |assignment|
    #   # p assignment
    #   # p assignment[0]
    #   # p assignment[1]
    #   if assignment[0] == @current_user && assignment[1] == @current_user
    #     pairs = participants.shuffle
    #     assignments = pairs.zip(participants)
    #   else
    #   @gift_exchange = GiftExchange.create(recipient: assignment[0], sender: assignment[1], event_id: 1, wishlist_item_id: 1)
    #   end
  #   end
  # end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    current_user
    @events = Event.all
    @user_events_participations = Participation.find_by(participant_id: current_user.id)

    if @events.count and @user_events_participations 
      @user_event_attendee = @user_events_participations.event
    end 

  end

  # GET /events/1
  # GET /events/1.json
  def show

    @event = Event.find_by(id: params[:id])
    if @event.participants.count > 1  
      @event.create_pairs
      #binding.pry
      @gift_exchanges = GiftExchange.where(event_id: @event.id)
      #if @gift_exchanges
      #  @recipient = @gift_exchanges.recipient
      #  @recipient_wishlist = Wishlist.find_by(user_id: @recipient.id)
      #end 
    end 

    # @event.create_pairs
#     pre-merge master
#     @gift_exchange = GiftExchange.find_by(event_id: params[:event_id])
    # binding.pry
    # @wishlist = Wishlist.find_by(user_id: @gift_exchange.recipient_id)
    # render "participations/_secret_santa"

  end



  # GET /events/new
  def new
    @event = Event.new
  end



  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)
    
    respond_to do |format|
      if @event.save
        format.html { redirect_to @event, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy

    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end



  private
    # Use callbacks to share common setup or constraints between actions.

    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:name, :description, :start_date, :end_date, :suggested_budget, :creator_id)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for @event do |form| %>
  <% if event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :event_name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description, id: :event_description %>
  </div>



  <div class="field">
    <%= form.label :suggested_budget %>
    <%= form.text_field :suggested_budget, id: :event_suggested_budget %>
  </div>
  <%= form.hidden_field :creator_id, value: current_user.id%>

      <%= form.submit 'Create exchange', class: "btn btn-primary btn-lg" %>
      <% end %>
      <br>
      <%= link_to 'Back', events_path, class: "btn btn-primary" %>
    </div>


  </div>
</div>

app/views/events/edit.html.erb
<h1>Editing Event</h1>

<%= render 'form', event: @event %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<div class="container">
<p id="notice"><%= notice %></p>

<div>

<button type="button" class="btn btn-light"><%= link_to 'Create New Exchange', new_event_path %></button>


</div>

<h1>All Exchanges</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Suggested budget</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div>

    <% current_user.events.uniq.each do |event| %>

        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td>$<%= event.suggested_budget %></td>
        <td><%= event.creator.first_name %> <%=event.creator.last_name%></td>
        <td><%= link_to 'Details', event %></td>
      </tr>
    <% end %>
  </div>
  </tbody>
</table>
</div>

<div class="container">
<p id="notice"><%= notice %></p>

<h1>Hosting Exchanges</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Suggested budget</th>
      <th>Owner</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <div>
    <% @events.each do |event| %>

    <% if event.creator_id == current_user.id %>
      <tr>
        <td><%= event.name %></td>
        <td><%= event.description %></td>
        <td>$<%= event.suggested_budget %></td>
        <td><%= event.creator.first_name %> <%=event.creator.last_name%></td>
        <td><%= link_to 'Details', event %></td>
        <td><%= link_to 'Edit event', edit_event_path(event) %></td>
        <td><%= link_to 'Delete', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>

    <% end %>
  </div>
  </tbody>
</table>
</div>

app/views/events/new.html.erb
<h1>New Exchange</h1>

<%= render 'form', event: @event %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p><h3><%= @event.name %></h3></p>

<p>
  <strong>Description:</strong>
  <%= @event.description %>
</p>


<p>
  <strong>Suggested budget:</strong>
  $<%= @event.suggested_budget %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @event.creator.first_name %> <%=@event.creator.last_name %>
</p>


<p><strong>Participants:</strong></p>
  <p><%= link_to "Add participants", new_event_participation_path(@event) %></p>


  <ol>
  <%@event.participants.each do |participant| %>
  <li><%=participant.first_name%> <%=participant.last_name%></li>
  <% end %>
  </ol>


<br />

<div id="secret">
 <p><b>Pairs created: </b></p>
 <% participants = @event.participants %>
 <% nb_participants = participants.length %>
 <% if nb_participants > 0 %>
 <% temp = participants[0] %>
 <% assignees = Array.new(nb_participants, 0) %>
   <% participants.each_with_index do |elt, index| %>
    <% assignees[index] = participants[index+1] %>
   <% end %>
 <% assignees[(nb_participants-1)] = temp %>
 <% end %>
</div>




<div>
<% if nb_participants > 0 %>
  <% assignees.each_with_index do |elt, index| %>
  <% current_participant = participants[index] %>
  <% if current_user.first_name == current_participant.first_name %>
  <% assignee = assignees[index] %>
   <p><%= current_participant.first_name %>, you have: <a href="/wishlists/<%= assignee.id %>"><%= assignee.first_name %></a></p>
    <br>
  <% end %>
  <% end %>
<% end %>
</div>



<br>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', wishlists_path %>