config/routes.rb
Rails.application.routes.draw do
  resources :wishlist_items
  resources :gifts
  resources :wishlists
  devise_for :admins
  resources :events
  devise_for :users
  resources :welcome
  resources :events do
   resources :participations
 end
  resources :users

  get '/events/:id/participations', to: 'participations#create'
  post '/events/:id/participations', to: 'participations#create'

  root to: redirect('/welcome/show')
  post '/search', to: 'gifts#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/gift.rb
class Gift < ApplicationRecord
	has_many :wishlist_items
	has_many :wishlists, through: :wishlist_items

  def add_wanted_gifts(params)
    # puts "***************add_wanted_gifts_method*************"
    # binding.pry
    params[:gift].values.select{|item| item[:want]}
  end


end

app/controllers/gifts_controller.rb
class GiftsController < ApplicationController
  before_action :set_gift, only: [:show, :edit, :update, :destroy]

  # GET /gifts
  # GET /gifts.json
  def index
    @gifts = Gift.all
  end

  # GET /gifts/1
  # GET /gifts/1.json
  def show
  end

  # GET /gifts/new
  def new
    @gift = Gift.new
  end

  # GET /gifts/1/edit
  def edit
  end

  def search

      p params
     @results = Wishlist.new.parsed_info_by_keyword(params["gifts"]["keyword"])
       respond_to do |format|
       #if @gift.save
        format.js
        format.html { render "new", locals: {results: @results} }
        # format.json { render :show, status: :created, location: @gift }
       #else
         # format.html { render :new }
         # format.json { render json: @gift.errors, status: :unprocessable_entity }
       #end
     end

  end
  # POST /gifts
  # POST /gifts.json
   def create
    items = Gift.new.add_wanted_gifts(params)
    items.each do |item|
      gift = Gift.create(name: item[:name], price: item[:price].gsub("/","").gsub("$","").to_f,
        url: item[:url], category:item[:category].gsub("/",""))
      wishlist_item = WishlistItem.create(wishlist_id: current_user.wishlists.first.id, gift_id: gift.id)
      redirect_to wishlists_path
    end



    # p params
    # binding.pry
    # p params["gift"]["keyword"]
    # p gift_params
    # p @results = Wishlist.new.parsed_info_by_keyword(params["gift"]["keyword"])
    #@results = Wishlist.new.parsed_info_by_keyword(params[:gift][:category])
    # submit the form

    # go to the page with the list of results of the search

    # select one link, save the url into the database

    # Gift.new(name: gift_params, price: 19.99, url: "www.example.com", category: "kitchen")

    #@gift = Gift.new(name: gift_params["name"], price: 19.99, url: "www.example.com", category: gift_params["name"])


   end

  # PATCH/PUT /gifts/1
  # PATCH/PUT /gifts/1.json
  def update
    respond_to do |format|
      if @gift.update(gift_params)
        format.html { redirect_to @gift, notice: 'Gift was successfully updated.' }
        format.json { render :show, status: :ok, location: @gift }
      else
        format.html { render :edit }
        format.json { render json: @gift.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /gifts/1
  # DELETE /gifts/1.json
  def destroy
    @gift.destroy
    respond_to do |format|
      format.html { redirect_to gifts_url, notice: 'Gift was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_gift
      @gift = Gift.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def gift_params
      params.require(:gift).permit(:name, :price, :url, :category)
    end
end

app/helpers/gifts_helper.rb
module GiftsHelper
end

app/views/gifts/_form.html.erb
<div style="width: 100%; overflow: hidden;">
    <div id="keyword-search" class="form-container" style="width: 600px; float: left;">
      <%= form_tag({ controller: "gifts", action: "search"}, method:"post", class: "form_stuff") do |form| %>
  <% if gift && gift.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(gift.errors.count, "error") %> prohibited this gift from being saved:</h2>

      <ul>
      <% gift.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <p>Search for a gift by <b>keyword</b></p>

  <div class="field">
    Keyword:
    <%= text_field(:gifts, :keyword, id: 'gift_name') %>
  </div>

  <div class="actions">

    <input type='submit' class="create_gift btn btn-primary" value="Search"/>
  </div>
<% end %>
</div>
</div>

app/views/gifts/_results.html.erb
<div class="results-container">
<% if results %>

  <form action="/gifts" method="POST">
    <input type="hidden" name="authenticity_token" value=<%= form_authenticity_token %>>
    <ul><% @results[:names].each_with_index do |item, index|%>
      <div class = "aws_results">
        <% image = @results[:images][index] %>
        <% link = @results[:urls][index] %>
          <input type='checkbox' name='gift[<%=index%>][want]'/>
          <input type="hidden" name='gift[<%=index%>][name]' value=<%=@results[:names][index]%> />
          <input type="hidden" name='gift[<%=index%>][price]' value=<%=@results[:prices][index]%> />
          <input type="hidden" name='gift[<%=index%>][url]' value=<%=link%> />
          <input type="hidden" name='gift[<%=index%>][category]' value=<%=@results[:categories][index]%> />
          <p>
            <img id="gift-result" class="img-fluid img-thumbnail" alt="Responsive image" src=<%=image%>>
            <br>
            <a href=<%=link%>>Item Details</a>
          </p>
          <!-- <p><img id="gift-result" src=<%=image%>><br><a href=<%=link%>>Item Details</a></p> -->
          <p><b>Name: </b><%=item%> | <b>Price: </b> <%=@results[:prices][index]%></p>
        </div>
        <% end %>

    </ul>

    <input type='submit' class="btn btn-primary" value="Add to Wishlist">
  
  </form>
<% end %>
</container>
</div>

app/views/gifts/edit.html.erb
<h1>Editing Gift</h1>

<%= render 'form', gift: @gift %>

<%= link_to 'Show', @gift %> |
<%= link_to 'Back', gifts_path %>

app/views/gifts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Gifts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Url</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @gifts.each do |gift| %>
      <tr>
        <td><%= gift.name %></td>
        <td><%= gift.price %></td>
        <td><%= gift.url %></td>
        <td><%= gift.category %></td>
        <td><%= link_to 'Show', gift %></td>
        <td><%= link_to 'Edit', edit_gift_path(gift) %></td>
        <td><%= link_to 'Delete', gift, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Gift', new_gift_path %>

app/views/gifts/new.html.erb
<div>
<h1>Add a new gift</h1>
</div>
<%= render 'form', gift: @gift %>
<div class="res" align="center" >
  <%= render partial: 'results' , locals: {results: @results} %>

</div>
 <%= link_to 'Back to your wishlist', wishlists_path %>

app/views/gifts/search.js.erb
$(".res").html("<%= escape_javascript(render partial: 'results' , locals: {results: @results}) %>")

app/views/gifts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @gift.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @gift.price %>
</p>

<p>
  <strong>Url:</strong>
  <%= @gift.url %>
</p>

<p>
  <strong>Category:</strong>
  <%= @gift.category %>
</p>

<%= link_to 'Edit', edit_gift_path(@gift) %> |
<%= link_to 'Back', gifts_path %>