config/routes.rb
Rails.application.routes.draw do
  resources :wishlist_items
  resources :gifts
  resources :wishlists
  devise_for :admins
  resources :events
  devise_for :users
  resources :welcome
  resources :events do
   resources :participations
 end
  resources :users

  get '/events/:id/participations', to: 'participations#create'
  post '/events/:id/participations', to: 'participations#create'

  root to: redirect('/welcome/show')
  post '/search', to: 'gifts#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/wishlist_item.rb
class WishlistItem < ApplicationRecord
	belongs_to :wishlist
	belongs_to :gift
end

app/controllers/wishlist_items_controller.rb
class WishlistItemsController < ApplicationController
  before_action :set_wishlist_item, only: [:show, :edit, :update, :destroy]

  # GET /wishlist_items
  # GET /wishlist_items.json
  def index
    @wishlist_items = WishlistItem.all
  end

  # GET /wishlist_items/1
  # GET /wishlist_items/1.json
  def show
  end

  # GET /wishlist_items/new
  def new
    @wishlist_item = WishlistItem.new
  end

  # GET /wishlist_items/1/edit
  def edit
  end

  # POST /wishlist_items
  # POST /wishlist_items.json
  def create
    @wishlist_item = WishlistItem.new(wishlist_item_params)

    respond_to do |format|
      if @wishlist_item.save
        format.html { redirect_to @wishlist_item, notice: 'Wishlist item was successfully created.' }
        format.json { render :show, status: :created, location: @wishlist_item }
      else
        format.html { render :new }
        format.json { render json: @wishlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /wishlist_items/1
  # PATCH/PUT /wishlist_items/1.json
  def update
    respond_to do |format|
      if @wishlist_item.update(wishlist_item_params)
        format.html { redirect_to @wishlist_item, notice: 'Wishlist item was successfully updated.' }
        format.json { render :show, status: :ok, location: @wishlist_item }
      else
        format.html { render :edit }
        format.json { render json: @wishlist_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /wishlist_items/1
  # DELETE /wishlist_items/1.json
  def destroy
    @wishlist_item.destroy
    respond_to do |format|
      format.html { redirect_to wishlist_items_url, notice: 'Wishlist item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_wishlist_item
      @wishlist_item = WishlistItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def wishlist_item_params
      params.require(:wishlist_item).permit(:wishlist_id, :gift_id)
    end
end

app/helpers/wishlist_items_helper.rb
module WishlistItemsHelper
end

app/views/wishlist_items/_form.html.erb
<%= form_with(model: wishlist_item, local: true) do |form| %>
  <% if wishlist_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(wishlist_item.errors.count, "error") %> prohibited this wishlist_item from being saved:</h2>

      <ul>
      <% wishlist_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :wishlist_id %>
    <%= form.number_field :wishlist_id, id: :wishlist_item_wishlist_id %>
  </div>

  <div class="field">
    <%= form.label :gift_id %>
    <%= form.number_field :gift_id, id: :wishlist_item_gift_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/wishlist_items/edit.html.erb
<h1>Editing Wishlist Item</h1>

<%= render 'form', wishlist_item: @wishlist_item %>

<%= link_to 'Show', @wishlist_item %> |
<%= link_to 'Back', wishlist_items_path %>

app/views/wishlist_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Wishlist Items</h1>

<table>
  <thead>
    <tr>
      <th>Wishlist</th>
      <th>Gift</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @wishlist_items.each do |wishlist_item| %>
      <tr>
        <td><%= wishlist_item.wishlist_id %></td>
        <td><%= wishlist_item.gift_id %></td>
        <td><%= link_to 'Show', wishlist_item %></td>
        <td><%= link_to 'Edit', edit_wishlist_item_path(wishlist_item) %></td>
        <td><%= link_to 'Delete', wishlist_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Wishlist Item', new_wishlist_item_path %>

app/views/wishlist_items/new.html.erb
<h1>New Wishlist Item</h1>

<%= render 'form', wishlist_item: @wishlist_item %>

<%= link_to 'Back', wishlist_items_path %>

app/views/wishlist_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Wishlist:</strong>
  <%= @wishlist_item.wishlist_id %>
</p>

<p>
  <strong>Gift:</strong>
  <%= @wishlist_item.gift_id %>
</p>

<%= link_to 'Edit', edit_wishlist_item_path(@wishlist_item) %> |
<%= link_to 'Back', wishlist_items_path %>