config/routes.rb
Rails.application.routes.draw do
  resources :wishlist_items
  resources :gifts
  resources :wishlists
  devise_for :admins
  resources :events
  devise_for :users
  resources :welcome
  resources :events do
   resources :participations
 end
  resources :users

  get '/events/:id/participations', to: 'participations#create'
  post '/events/:id/participations', to: 'participations#create'

  root to: redirect('/welcome/show')
  post '/search', to: 'gifts#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GiftSwap</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="http://clipart-library.com/images/pToA66anc.png" sizes="16x16" type="image/png"/>
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/css/bootstrap-theme.css">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" rel="stylesheet" type="text/css"/>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js" type="text/javascript"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" type="text/javascript"></script>
    <%= stylesheet_link_tag 'application' %>
    <script src="https://code.jquery.com/jquery-3.2.1.min.js" integrity="sha256-hwg4gsxgFZhOsEEamdOYGBf13FyQuiTwlAQgxVSNgt4=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <nav class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">giftSwap <span class="glyphicon glyphicon-gift" aria-hidden="true"></span></a>
        </div>
        <div class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
            <p class="navbar-text pull-right">
            <% if user_signed_in? %>
              Logged in as <strong><%= current_user.email %></strong>

              <li class="nav-link"><%= link_to 'Events', events_path, :class => 'navbar-link' %></li>
              <li class="nav-link"><%= link_to 'Your Wishlist', wishlists_path, :class=> 'navbar-link'%></li>
              <li class="nav-link"><%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %></li>
              <li class="nav-link"><%= link_to 'About', welcome_index_path, :class => 'navbar-link' %></li>
              <li class="nav-link"><%= link_to "Logout", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %></li>
            <% else %>
              <li class="nav-link"><%= link_to "Sign up", new_user_registration_path, :class => 'navbar-link'  %></li>
              <li class="nav-link"><%= link_to "Login", new_user_session_path, :class => 'navbar-link'  %></li>
            <% end %>
            </p>
          </ul>
        </div>
      </div>
    </nav>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
  <script src="//maxcdn.bootstrapcdn.com/bootstrap/3.0.3/js/bootstrap.js"></script>
  </body>
  <footer>
      <div class="container">
    giftSwap <%= Time.now.year %>
    </div>
  </footer>
</html>